### ISSUE TITLE
 Swift Compiler Errors in Esewa Flutter SDK during iOS Build

### ISSUE THREAD

**Issue by rabindra-vrit** [devSumanrazz/esewa_sdk#4]
I encountered multiple Swift compiler errors while building my Flutter app for iOS with the Esewa Flutter SDK. The errors include the following:

ValidationType is not a member type of class EsewaSDK.EsewaSDK.
Reachability is not a member type of class EsewaSDK.EsewaSDK.
FormTextField is not a member type of class EsewaSDK.EsewaSDK.
TextFieldValidation is not a member type of class EsewaSDK.EsewaSDK.
These errors are occurring in the generated iOS module files. Below are the details:

Flutter Version: 3.24.5
Esewa Flutter SDK Version: '>=3.0.6 <4.0.0'
Xcode Version: 16.1
Swift Version: 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Platform: iOS
Device: iOS 18.0 Simulator
Steps to Reproduce:
Add esewa_flutter_sdk to pubspec.yaml.
Run flutter pub get and build the project using flutter build ios.
Errors appear during the build process in Xcode.
Expected Behavior:
The app should compile and build successfully without any Swift compiler errors.

Actual Behavior:
The build fails with the above-mentioned Swift compiler errors in the EsewaSDK module files.

Possible Solutions:
Ensure compatibility with Swift 6.0.2.
Verify that the necessary type definitions are included in the EsewaSDK.

**Comment by sumanrajpathak** [comment]
@rabindra-vrit As the package is discontinued, and there are no plans to release any new updates. You might have to look for alternatives for the package
